services:
    dev:
        build:
            context: .
            dockerfile: dev.Dockerfile
        ports:
            - "5173:5173"
        volumes:
            - .:/app
            - /app/node_modules
    build:
        profiles: ["build"]
        build:
            context: .
            dockerfile: dev.Dockerfile
        volumes:
            - .:/app
            - /app/node_modules
        command: sh -c "npm install && npm run build"
